# 标题
title = '西游记'

# 章节分隔正则匹配表达式
chapter_filter_pattern = '第\w+回'

# 章节描述
chapter_name = '章节'

# 角色配置
roles = [
    {'filter_words': ['唐三藏', '唐僧', '三藏', '玄奘', '师父', '江流', '金蝉', '唐长老', '旃檀功德佛']},
    {'filter_words': ['孙悟空', '悟空', '大圣', '石猴', '弼马温', '妖猴', '猴王', '行者', '猴哥', '大师兄', '斗战胜佛']},
    {'filter_words': ['猪八戒', '悟能', '天蓬元帅', '八戒', '呆子', '二师兄', '猪刚鬛', '净坛使者']},
    {'filter_words': ['沙僧', '沙和尚', '悟净', '卷帘大将', '沙师弟', '金身罗汉']},
    {'filter_words': ['白龙马', '三太子', '八部天龙马', '白马']},
    {'filter_words': ['如来佛祖', '如来']},
    {'filter_words': ['弥勒佛', '弥勒']},
    {'filter_words': ['燃灯古佛', '弥勒']},
    {'filter_words': ['观音菩萨', '观音', '菩萨']},
    {'filter_words': ['陈光蕊', '光蕊']},
    {'filter_words': ['殷温娇', '殷小姐']},
    {'filter_words': ['唐太宗', '太宗', '唐王']},
    {'filter_words': ['魏征']},
    {'filter_words': ['叔宝']},
    {'filter_words': ['敬德']},
    {'filter_words': ['法明和尚', '法明']},
    {'filter_words': ['刘洪']},
    {'filter_words': ['李彪']},
    {'filter_words': ['文殊菩萨']},
    {'filter_words': ['普贤菩萨']},
    {'filter_words': ['地藏王菩萨']},
    {'filter_words': ['谛听']},
    {'filter_words': ['菩提祖师', '祖师']},
    {'filter_words': ['阿难']},
    {'filter_words': ['伽叶']},
    {'filter_words': ['灵吉菩萨']},
    {'filter_words': ['毗蓝婆菩萨']},
    {'filter_words': ['孔雀明王']},
    {'filter_words': ['玉皇大帝', '玉帝']},
    {'filter_words': ['王母娘娘', '王母']},
    {'filter_words': ['天皇大帝']},
    {'filter_words': ['紫微大帝']},
    {'filter_words': ['长生大帝']},
    {'filter_words': ['青华大帝']},
    {'filter_words': ['东华帝君']},
    {'filter_words': ['真武大帝']},
    {'filter_words': ['元始天尊']},
    {'filter_words': ['灵宝天尊']},
    {'filter_words': ['太上老君', '老君']},
    {'filter_words': ['千里眼']},
    {'filter_words': ['顺风耳']},
    {'filter_words': ['雷公']},
    {'filter_words': ['电母']},
    {'filter_words': ['风伯']},
    {'filter_words': ['雨师']},
    {'filter_words': ['赤脚大罗仙']},
    {'filter_words': ['推云童子', '云童']},
    {'filter_words': ['布雾郎君']},
    {'filter_words': ['太白金星', '金星']},
    {'filter_words': ['木德星君', '木德星官']},
    {'filter_words': ['嫦娥', '广寒仙子', '姮娥仙子']},
    {'filter_words': ['李靖', '托塔天王', '李天王']},
    {'filter_words': ['金吒']},
    {'filter_words': ['木吒', '惠岸', '木叉']},
    {'filter_words': ['哪吒']},
    {'filter_words': ['巨灵神']},
    {'filter_words': ['东方持国天王', '持国天王']},
    {'filter_words': ['南方增长天王', '增长天王']},
    {'filter_words': ['西方广目天王', '广目天王']},
    {'filter_words': ['北方多闻天王', '多闻天王']},
    {'filter_words': ['杨戬', '二郎显圣真君', '二郎神', '真君']},
    {'filter_words': ['哮天犬']},
    {'filter_words': ['敖广', '东海龙王']},
    {'filter_words': ['敖钦', '南海龙王']},
    {'filter_words': ['敖闰', '西海龙王']},
    {'filter_words': ['敖顺', '北海龙王']},
    {'filter_words': ['秦广王']},
    {'filter_words': ['泾河龙王']},
    {'filter_words': ['崔玨']},
    {'filter_words': ['阎罗王']},
    {'filter_words': ['混世魔王', '魔王']},
    {'filter_words': ['寅将军']},
    {'filter_words': ['熊山军']},
    {'filter_words': ['特处士']},
    {'filter_words': ['黑风怪']},
    {'filter_words': ['白衣秀士']},
    {'filter_words': ['凌虚子']},
    {'filter_words': ['黄风怪']},
    {'filter_words': ['镇元大仙', '镇元子']},
    {'filter_words': ['清风']},
    {'filter_words': ['明月']},
    {'filter_words': ['白骨精', '白骨夫人', '尸魔']},
    {'filter_words': ['黄袍怪']},
    {'filter_words': ['金角大王']},
    {'filter_words': ['银角大王']},
    {'filter_words': ['狮猁怪']},
    {'filter_words': ['红孩儿']},
    {'filter_words': ['鼍龙']},
    {'filter_words': ['虎力大仙']},
    {'filter_words': ['鹿力大仙']},
    {'filter_words': ['羊力大仙']},
    {'filter_words': ['灵感大王']},
    {'filter_words': ['独角兕大王']},
    {'filter_words': ['如意真仙']},
    {'filter_words': ['女儿国国王']},
    {'filter_words': ['蝎子精']},
    {'filter_words': ['六耳猕猴']},
    {'filter_words': ['牛魔王', '平天大圣']},
    {'filter_words': ['铁扇公主']},
    {'filter_words': ['万圣龙王']},
    {'filter_words': ['万圣公主']},
    {'filter_words': ['树精']},
    {'filter_words': ['黄眉大王']},
    {'filter_words': ['蟒蛇精']},
    {'filter_words': ['赛太岁']},
    {'filter_words': ['蜘蛛精']},
    {'filter_words': ['百眼魔君']},
    {'filter_words': ['黄牙老象']},
    {'filter_words': ['大鹏金翅鸟']},
    {'filter_words': ['白鹿精']},
    {'filter_words': ['白面狐狸精']},
    {'filter_words': ['地涌夫人']},
    {'filter_words': ['灭法国国王']},
    {'filter_words': ['南山大王']},
    {'filter_words': ['九灵元圣']},
    {'filter_words': ['辟寒大王']},
    {'filter_words': ['辟暑大王']},
    {'filter_words': ['辟尘大王']},
    {'filter_words': ['玉兔精']},
    {'filter_words': ['大白龟']},
]
