# 标题
title = '红楼梦'

# 章节分隔正则匹配表达式
chapter_filter_pattern = '第\w+回'

# 章节描述
chapter_name = '章节'

# 角色配置
roles = [
    {'filter_words': ['贾宝玉', '宝玉']},
    {'filter_words': ['林黛玉', '黛玉', '林妹妹', '林姑娘']},
    {'filter_words': ['薛宝钗', '宝钗', '薛妹妹']},
    {'filter_words': ['贾代化']},
    {'filter_words': ['贾代善']},
    {'filter_words': ['贾赦']},
    {'filter_words': ['贾政']},
    {'filter_words': ['贾敷']},
    {'filter_words': ['贾敬']},
    {'filter_words': ['贾珍']},
    {'filter_words': ['贾蓉']},
    {'filter_words': ['贾珠']},
    {'filter_words': ['贾兰']},
    {'filter_words': ['贾琏', '琏爷']},
    {'filter_words': ['贾雨村', '雨村']},
    {'filter_words': ['冷子兴', '子兴']},
    {'filter_words': ['封肃']},
    {'filter_words': ['林如海', '如海']},
    {'filter_words': ['贾元春', '元春', '元妃']},
    {'filter_words': ['贾迎春', '迎春']},
    {'filter_words': ['贾探春', '探春']},
    {'filter_words': ['贾惜春', '惜春']},
    {'filter_words': ['王熙凤', '熙凤', '凤姐']},
    {'filter_words': ['贾母']},
    {'filter_words': ['王夫人']},
    {'filter_words': ['邢夫人']},
    {'filter_words': ['尤氏']},
    {'filter_words': ['李纨']},
    {'filter_words': ['秦可卿', '秦氏']},
    {'filter_words': ['王嬷嬷']},
    {'filter_words': ['李嬷嬷']},
    {'filter_words': ['雪雁']},
    {'filter_words': ['紫鹃', '鹦哥']},
    {'filter_words': ['麝月']},
    {'filter_words': ['秋纹']},
    {'filter_words': ['晴雯']},
    {'filter_words': ['茜雪']},
    {'filter_words': ['坠儿']},
    {'filter_words': ['入画']},
    {'filter_words': ['司棋']},
    {'filter_words': ['四儿']},
    {'filter_words': ['春燕', '小燕']},
    {'filter_words': ['鸳鸯']},
    {'filter_words': ['碧痕']},
    {'filter_words': ['芳宫']},
    {'filter_words': ['香菱']},
    {'filter_words': ['袭人']},
    {'filter_words': ['莺儿']},
    {'filter_words': ['金钏']},
    {'filter_words': ['彩云']},
    {'filter_words': ['彩霞']},
    {'filter_words': ['宝珠']},
    {'filter_words': ['林红玉', '小红']},
    {'filter_words': ['史湘云', '湘云']},
    {'filter_words': ['妙玉']},
    {'filter_words': ['李守']},
    {'filter_words': ['英莲']},
    {'filter_words': ['刘姥姥']},
    {'filter_words': ['平儿']},
    {'filter_words': ['薛姨妈']},
    {'filter_words': ['赵姨娘']},
    {'filter_words': ['薛蝌']},
    {'filter_words': ['秦业']},
    {'filter_words': ['秦钟']},
    {'filter_words': ['李贵']},
    {'filter_words': ['贾瑞']},
    {'filter_words': ['贾菌']},
    {'filter_words': ['贾璜']},
    {'filter_words': ['夏金桂', '金桂']},
    {'filter_words': ['金荣']},
    {'filter_words': ['茗烟']},
    {'filter_words': ['贾巧姐', '巧姐']},
    {'filter_words': ['玉菡']},
    {'filter_words': ['薛宝琴', '宝琴']},
]
